libsysprof-capture: Drop duplicate struct typedefs
All three of these structs are already defined in
`sysprof-capture-types.h`, which is included from these three headers.

Drop the duplicate definition to silence the Clang warning:
```
In file included from /opt/gnome/install/include/sysprof-4/sysprof-capture.h:63:
/opt/gnome/install/include/sysprof-4/sysprof-capture-cursor.h:67:38: warning: redefinition of typedef 'SysprofCaptureCursor' is a C11 feature [-Wtypedef-redefinition]
typedef struct _SysprofCaptureCursor SysprofCaptureCursor;
                                     ^
/opt/gnome/install/include/sysprof-4/sysprof-capture-types.h:98:41: note: previous definition is here
typedef struct _SysprofCaptureCursor    SysprofCaptureCursor;
```

Signed-off-by: Philip Withnall <pwithnall@endlessos.org>